language:       scala
scala:
              - 2.12.2
jdk:
              - openjdk8
              - oraclejdk8
dist:           trusty
cache:
              - "~/.ivy2"
              - "~/.sbt"
install:
              - sudo apt-get update
              - sudo apt-get install zsh
              - sudo chmod +x scripts/*
              - scripts/sbt update
script:         scripts/run-all-tests.sh
after_script:
              - scripts/prepare-test-results-for-ci.sh
notifications:
  email:
    on_success: never
    on_failure: change
